version: "3.8"


services:

  grafana:
    image: grafana/grafana:11.5.2
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]


volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=GMS-User,password=ATS1g2m3s!,dir_mode=0777"
      device: "//10.101.102.100/GMS/poc/grafana/"