version: "3.8"


services:

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/etc/prometheus
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1




volumes:
  prometheus:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=GMS-User,password=ATS1g2m3s!,domain=svrFsTest25v544,nolock,soft,rw,file_mode=0777,dir_mode=0777"
      device: "//10.101.102.100/GMS/poc"

