version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-storage:/etc/grafana
      - grafana-provisioning:/grafana-provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_STORAGE=/grafana-provisioning
    deploy:
      placement:
        constraints:
          - node.platform.os == linux

volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=GMS-User,password=ATS1g2m3s!,vers=3.0,noperm,file_mode=0777,dir_mode=0777"
      device: "//10.101.102.100/GMS/poc/grafana/data"
  grafana-storage:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=GMS-User,password=ATS1g2m3s!,vers=3.0,noperm,file_mode=0777,dir_mode=0777"
      device: "//10.101.102.100/GMS/poc/grafana/storage"
  grafana-provisioning:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=GMS-User,password=ATS1g2m3s!,vers=3.0,noperm,file_mode=0777,dir_mode=0777"
      device: "//10.101.102.100/GMS/poc/grafana/provisioning"
